
# get home
GET http://localhost:5001

# get all product
###
GET http://localhost:5001/products


# cari berdasarkan nim
###
GET http://localhost:5001/cari/565

# cari berdasarkan id
###
GET http://localhost:5001/product/23


# add data 
###
POST http://localhost:5001/product
Content-Type: application/json
  
  {
    "nim":2,
    "product_name":"",
    "product_price" : 200
}


# edit data 
###
put http://localhost:5001/product
Content-Type: application/json
  
  {
    "nim": 477,
    "product_name": "saya",
    "product_price": 12000
}

# delete data
###
DELETE http://localhost:5001/product
Content-Type: application/json

{
  "nim": 474

}